# Generated by Django 5.0.4 on 2024-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_purchaseorder_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(default=0, null=True),
        ),
    ]
